### ISSUE TITLE
Please delete this issue

### ISSUE THREAD

**Issue by henriquebuzon** [Dr-Dreams/EasyApplyBot#2]

**Comment by henriquebuzon** [comment]
> 

I already managed to make it work. All you need to do on Linux is run "sudo bash venv/bin/activate" with "bash" instead of "source". It works like a charm, thank you so much for sharing it.

However, could you please delete this issue? I tried to delete it myself, but it seems that only the repository administrator is allowed to do so.

Again, thank you so much!

**Comment by Dr-Dreams** [comment]
Great. Now, I am deleting this issue.

**Comment by henriquebuzon** [comment]
Thanks. The reason I am asking you to delete is because it shows up on my activity feed. It is a little embarrassing when potential employers visit my profile and notice that I am using a Linkedin bot.

It seems you just closed the issue as completed so it is still showing up on my activity feed. Could you please delete it instead?

Sorry I have to ask you to do this but I tried to delete it myself for quite some time and really there is no way I can do it. That is just how Github is.
