### ISSUE TITLE
Issue with running Main.py

### ISSUE THREAD

**Issue by HoodedCoder17** [Dr-Dreams/EasyApplyBot#3]
Facing below issue while running Main.py 

`_File "C:\Users\RAHUL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config.yaml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "config.yaml", line 176, column 3_`

**Comment by Dr-Dreams** [comment]
# The problem with your .yaml file

I reviewed your .yaml file and found that your format is not valid.

Please follow this format:-
 
```diff
-experience: 2
  Accounting/Auditing: 0
   .................
+ experience:
  Accounting/Auditing: 0
   .................
```
Please read [Readme.md](https://github.com/Dr-Dreams/EasyApplyBot/blob/main/README.md)
