### ISSUE TITLE
so many unprepared questions

### ISSUE THREAD

**Issue by yemins** [Dr-Dreams/EasyApplyBot#4]
Edit: Follow up question to the one below, what if it answered yes to all questions not defined in config.yaml...

was wondering if there was a way to add answers to these so it can automatically fill them out?

Unprepared Questions file:

**Comment by Dr-Dreams** [comment]
yes, you can add your answer in Unprepared Questions file

**Comment by dankstarr** [comment]
@Dr-Dreams  What's the format for adding answers in the  Unprepared Questions file? Yes/no for radio or True/False for radio? 
Do I just add the values in the thrid column?
