### ISSUE TITLE
Checkbox not ticking

### ISSUE THREAD

**Issue by dankstarr** [Dr-Dreams/EasyApplyBot#6]
Hi, 
I have noticed that it doesn't tick the checkboxes sometimes, such as privacy policy.

Also, is there a possibility to make it select 'yes' for all unanswered questions? Since it mostly skips the applications with them and a simple "yes" would suffice

**Comment by Dr-Dreams** [comment]
Sorry for late reply. I will update the repo.
Thanks for telling me..
